sudo: required
language: c
dist: xenial

matrix:
  include:
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"

    - os: osx
      osx_image: xcode10

    - os: osx
      osx_image: xcode10.1

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential gcc-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y bash build-essential autoconf autotools-dev libtool cmake libudev-dev libavahi-compat-libdnssd-dev libusb-1.0-0-dev fxload libcurl4-gnutls-dev libgphoto2-dev git curl dpkg fakeroot fxload libusb-1.0-0 libgudev-1.0-0 libgphoto2-6 libavahi-compat-libdnssd1 psmisc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh tools/cltools.sh ; fi
  - eval "${MATRIX_EVAL}"

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=$MSBUILD_PATH:$PATH && cd indigo_windows && MSBuild.exe "./indigo_windows.sln" /property:Platform="x86" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make package && sudo dpkg --install indigo*.deb && sudo ldconfig ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then indigo_test/test_suite.sh --driver-test --format-test indigo_ccd_simulator --capture-test indigo_ccd_simulator ; fi
